// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwkmzukogxonrqcsglnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3a216dWtvZ3hvbnJxY3NnbG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODI5MzAsImV4cCI6MjA3MTY1ODkzMH0.-4UO99oKDNpHCpNpRyRSDmXXM_niyEts-mc_NLosG5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});